## 00. Pytorch Fundamentals

In [1]:
print("Hello I am excited to learn Pytorch today!")

Hello I am excited to learn Pytorch today!


In [2]:
!nvidia-smi


Sun Jul 28 14:52:39 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   53C    P0             29W /   80W |     823MiB /   8192MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
print(torch.__version__)

2.0.0+cu117


### Introduction to tensors - main building block of DL

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Puthon Int
scalar.item()

7

In [7]:
# vector

vector = torch.tensor([7, 10, 11])
vector

tensor([ 7, 10, 11])

In [8]:
# vector.item() # it doesnt work on multiple elemnts
vector.tolist()

[7, 10, 11]

In [9]:
vector.ndim # Number of square brackets

1

In [10]:
vector.shape # Number of elemennts

torch.Size([3])

In [11]:
scalar.shape

torch.Size([])

In [12]:
scalar = torch.tensor(7)


In [13]:
scalar

tensor(7)

In [14]:
scalar.ndim

0

In [15]:
scalar.item()

7

In [16]:
vector = torch.tensor([7,7,8])

In [17]:
vector

tensor([7, 7, 8])

In [18]:
vector.ndim

1

In [19]:
scalar.shape

torch.Size([])

In [20]:
vector.shape

torch.Size([3])

In [21]:
MATRIX = torch.tensor([[9,8], [9,8]])
MATRIX

tensor([[9, 8],
        [9, 8]])

In [22]:
MATRIX.ndim

2

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [24]:
MATRIX[0]

tensor([9, 8])

In [25]:
Tensor = torch.tensor([ [ [3,4], [5,6]], [[6,7], [8,9]], [[0,0],[1,2]]])

In [26]:
Tensor

tensor([[[3, 4],
         [5, 6]],

        [[6, 7],
         [8, 9]],

        [[0, 0],
         [1, 2]]])

In [27]:
t1 = torch.tensor([[[1,2,3], [3,4,5], [6,7,8]]])

In [28]:
t1

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [29]:
t1.shape

torch.Size([1, 3, 3])

In [30]:
Tensor.shape

torch.Size([3, 2, 2])

In [31]:
t1[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
Tensor[1]

tensor([[6, 7],
        [8, 9]])

## Random Tensor

In [33]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0160, 0.8609, 0.3300, 0.3540],
        [0.0208, 0.2752, 0.2749, 0.2941],
        [0.5795, 0.0866, 0.8042, 0.8762]])

In [34]:
randome_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, no of channels

In [35]:
randome_image_size_tensor.shape, randome_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

#### zeroes and ones

In [36]:
#### zeroes and ones

In [37]:
zeroes = torch.zeros(size=(2,2))
zeroes

tensor([[0., 0.],
        [0., 0.]])

In [38]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
ones.dtype

torch.float32

In [40]:
t2 = torch.arange(0,10, 2)

In [41]:
five_zeroes = torch.zeros_like(t2)
five_zeroes

tensor([0, 0, 0, 0, 0])

In [42]:
five_zeroes.device

device(type='cpu')

In [43]:
five_zeroes.dtype

torch.int64

In [44]:
five_zeroes.shape

torch.Size([5])

### Manipulating tenosrs - tenosr Operations

In [45]:
# create tensor

In [46]:
tensor1 = torch.tensor([1,2,3])

tensor1+10

tensor([11, 12, 13])

In [47]:
tensor1*10

tensor([10, 20, 30])

In [48]:
tensor1-1

tensor([0, 1, 2])

In [49]:
torch.mul(tensor1, 10)

tensor([10, 20, 30])

In [50]:
torch.div(tensor1, 1)

tensor([1., 2., 3.])

### element wise multiplication

In [51]:
tensor_mult = tensor1 * tensor1
tensor_mult

tensor([1, 4, 9])

In [52]:
tensor_A = torch.tensor(
    [
        [1,2], [3, 4], [5,6]
    ]
)


In [60]:
tensor_B = torch.tensor(
    [
        [7,10], [10, 10], [5,6]
    ]
)

In [64]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  17],
        [ 61,  70,  39],
        [ 95, 110,  61]])

In [65]:
tensor_B.T

tensor([[ 7, 10,  5],
        [10, 10,  6]])

min, max,mean and sum

In [67]:
tensor_A = torch.arange(0,100,10)
tensor_A

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [69]:
torch.min(tensor_A).item()

0

In [70]:
torch.max(tensor_A).item()

90

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [80]:
tensor_A.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [81]:
torch.mean(tensor_A.type(torch.float32))

tensor(45.)

In [82]:
torch.sum(tensor_A)

tensor(450)

### Finding positional min and max

In [88]:
min_val = torch.argmin(tensor_A)

In [89]:
min_val

tensor(0)

In [90]:
max_val = torch.argmax(tensor_A)

In [91]:
max_val

tensor(9)

#### 3. Reshaping, Viewing and Stacking, Squeeze and Unsqueeze, Permuting tensors

- Reshape - reshapes to a defined shape
- View - return a  view of input tensor of a certain shape but, keep the same memory as orginal tensor
- Stacking - combine multiple tensors, on top of each other - vstack or side by side (hstack)
- Squeeze - remove one dim from tensors
- Unsqueeze - adds one dim to the target tensor
- Permute - Return a view of the input with dim permuted (swapped) in a certain way

In [92]:
x = torch.arange(0., 10.)

In [93]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
x.shape

torch.Size([10])

In [108]:
x_reshaped = x.reshape(1,10)
x_reshaped = x.reshape(1,10)
# x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
x.view(-1)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

- Stack

In [114]:
x_stack = torch.stack([x_reshaped, x_reshaped, x_reshaped], dim=-1)
x_stack
# x_stack.shape

tensor([[[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]])

In [115]:
tensor_zero = torch.zeros(2,1,2,1,2)
tensor_zero

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [118]:
squuezed_tensor = tensor_zero.squeeze()

In [119]:
squuezed_tensor.shape

torch.Size([2, 2, 2])

In [120]:
squuezed_tensor

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [123]:
x_squeeze = x_reshaped.squeeze()

In [124]:
x_squeeze

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [138]:
x_unsquueze = x_squeeze.unsqueeze(dim=0)

In [139]:
x_unsquueze.shape

torch.Size([1, 10])

- Permute

In [144]:
x = torch.rand(200, 100, 3)

In [145]:
x.shape

torch.Size([200, 100, 3])

In [146]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([3, 200, 100])

In [147]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [154]:
x[0][0]

tensor([1, 2, 3])

In [155]:
x[:,:,0]

tensor([[1, 4, 7]])

In [156]:
x[0,0,:]

tensor([1, 2, 3])

#### Pytorch tensors and Numpy

- torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
- torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [157]:
import numpy as np

In [159]:
arr = np.arange(1.0,8.0)
arr

array([1., 2., 3., 4., 5., 6., 7.])

In [160]:
t1 = torch.from_numpy(arr)
t1

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [162]:
t1_arr = t1.numpy()

In [163]:
t1_arr

array([1., 2., 3., 4., 5., 6., 7.])

In [164]:
t1_arr.dtype

dtype('float64')

#### 5. Pytorch Reproducibility

#### 5. Pytorch Reproducibility - Trying to take random out of random
- In short how neural net learns ->
- start with random numbers -> tensor operations -> update the random tensors to try and make them better represntations
- of the data -> again, again, again...

In [165]:
t1 = torch.rand(3,3)

In [166]:
t1

tensor([[0.7741, 0.2049, 0.2114],
        [0.2066, 0.7999, 0.3830],
        [0.7114, 0.7075, 0.8185]])

In [167]:
t2 = torch.rand(3,3)

In [168]:
t2

tensor([[0.0245, 0.5458, 0.8801],
        [0.7019, 0.5682, 0.8391],
        [0.2077, 0.7076, 0.7612]])

In [169]:
t1==t2

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [171]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
t3= torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
t4 = torch.rand(3,3)
t3==t4

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [172]:
!nvidia-smi

Sun Jul 28 23:01:15 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 ...    Off |   00000000:01:00.0  On |                  N/A |
| N/A   52C    P8             24W /   80W |     832MiB /   8192MiB |     66%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [173]:
torch.cuda.is_available()

True

In [174]:
torch.cuda.is_initialized()

False

In [175]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [176]:
device

'cuda'

In [177]:
torch.cuda.device_count()

1

In [178]:
t1 = torch.tensor([1,2,3])

t1.device

device(type='cpu')

In [180]:
t1_on_gpu = t1.to("cuda")
t1_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [185]:
tensor_back_on_cpu = t1_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])