# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.7352, 0.7805, 0.3544, 0.5887, 0.8979, 0.5806, 0.2743],
        [0.4262, 0.4274, 0.9120, 0.2597, 0.6186, 0.6726, 0.2520],
        [0.7131, 0.9520, 0.3453, 0.6441, 0.5264, 0.9334, 0.7327],
        [0.9249, 0.2671, 0.0788, 0.3660, 0.6883, 0.1855, 0.1214],
        [0.3174, 0.8329, 0.7625, 0.9544, 0.4816, 0.8106, 0.5103],
        [0.6817, 0.1563, 0.3698, 0.9803, 0.6640, 0.3593, 0.1910],
        [0.5025, 0.5064, 0.5593, 0.3716, 0.9057, 0.0436, 0.9465]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
random_tensor_another = torch.rand(1,7)
print(random_tensor_another)

# Perform matrix multiplication 

tensor_mult = torch.matmul(random_tensor,random_tensor_another.T)


tensor([[0.7115, 0.7217, 0.1121, 0.2179, 0.5650, 0.5017, 0.7590]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [13]:
# Set manual seed
MANUAL_SEED = 42
torch.manual_seed(MANUAL_SEED)
# Create two random tensors
t1 = torch.rand(7,7)
t2 = torch.rand(1,7)

print(t1)
print(t2)
# Matrix multiply tensors
res = torch.matmul(t1,t2.T)
print(res)


tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071]])
tensor([[1.3299],
        [1.8111],
        [1.3228],
        [0.9725],
        [1.8285],
        [1.4806],
        [2.0489]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(42)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
MANUAL_SEED = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(1234)
x = torch.rand(2,3).to(device)
y = torch.rand(2,3).to(device)

# res = torch.matmul(x,y)
print(x)
print(y)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(x, y.T)
print(res)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(torch.min(res))

# Find min
print(torch.max(res))

tensor(0.3647, device='cuda:0')
tensor(0.5617, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
print(torch.argmin(res))

# Find arg min
print(torch.argmax(res))

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
MANUAL_SEED = 7
torch.manual_seed(MANUAL_SEED)
# Create random tensor
a1 = torch.rand(1,1,1,10)
print(a1)
print(a1.shape)

# Remove single dimensions
new_a1 = a1.squeeze()
print(new_a1)
print(new_a1.shape)

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
